import AosModule from "./module/AosModule.js";
import SwiperModule from "./module/SwiperModule.js";
import Select2Module from "./module/Select2Module.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import ClickToggleModule from "./module/ClickToggleModule.js";
import HandleInputModule from "./module/HandleInputModule.js";
import HandleScroll from "./module/HandleScroll.js";
import SmoothScrollModule from "./module/SmoothScrollModule.js";
import FixedBar from "./module/FixedBar.js";
import FilterHandle from "./module/FilterHandle.js";
import HandleQuantity from "./module/HandleQuantity.js";
import HandleRatingStarModule from "./module/HandleRatingStarModule.js";
import ShowBtnMobile from "./module/ShowBtnMobile.js";
import ActiveStyleTab from "./module/ActiveStyleTab.js";
import ShowBoxSearchMb from "./module/ShowBoxSearchMb.js";
import isotopeModule from "./module/IsotopeModule.js";
import DatePickerModule from "./module/DatePickerModule.js";
import uploadFile from "./module/uploadFile.js";
import seeMoreModule from "./module/seeMoreModule.js";
window.addEventListener("DOMContentLoaded", () => {
    AosModule();
    TabModule();
    Select2Module();
    SwiperModule();
    GalleryModule();
    ClickToggleModule();
    HandleInputModule();
    HandleScroll();
    SmoothScrollModule();
    FixedBar();
    FilterHandle();
    HandleQuantity();
    HandleRatingStarModule();
    ShowBtnMobile();
    ActiveStyleTab();
    ShowBoxSearchMb();
    isotopeModule();
    DatePickerModule();
    uploadFile();
    seeMoreModule();
});